class Assignment {
  final int category;
  final String name;
  final String imagePath;
  final List<String> keyWords;

  Assignment(this.category, this.name, this.imagePath, this.keyWords);
}

///    ARTIK HER CATEGORY FARKLI BİR LİSTTE OLACAK VE ONLARIN HEPSİNİ TUTAN BİR LİST OLACAK

List<List<Assignment>> allData = [
  [
    Assignment(
      0,
      '3 Idıots',
      'Assets/Images/Movies/3 Idıots.jpg',
      [
        "3idiots",
        "3idıots",
        "3ıdıots",
        "3ıdiots",
        "üçaptal",
        "ücaptal",
        "threeidiots",
        "threeıdiots",
        "threeıdıots",
        "threeıdiots",
      ],
    ),
    Assignment(
      0,
      '7. Koğuştaki Mucize',
      'Assets/Images/Movies/7. Koğuştaki Mucize.jpg',
      [
        "7.koğuştakimucize",
        "7.koguştakimucize",
        "7.koguştakımucize",
        "7.koguştakımucıze",
        "7.koguştakımucize",
        "7.kogustakimucize",
        "7.koguştakimucıze",
        "yedincikoğuştakimucize",
        "yedıncıkoguştakımucıze",
        "miracleincellno.7",
        "miracleincellnoseven",
        "mıracleıncellnoseven",
      ],
    ),
    Assignment(
      0,
      '12 Maymun',
      'Assets/Images/Movies/12 Maymun.jpg',
      [
        "onikimaymun",
        "onıkimaymun",
        "onikımaymun",
        "onıkımaymun",
        "12monkeys",
        "12maymun",
        "twelvemonkeys",
      ],
    ),
    Assignment(
      0,
      '12 Öfkeli Adam',
      'Assets/Images/Movies/12 Öfkeli Adam.jpg',
      [
        "12öfkeliadam",
        "12ofkeliadam",
        "onikiöfkeliadam",
        "onikıöfkeliadam",
        "onıkiöfkeliadam",
        "onıkıöfkeliadam",
        "onıkıofkeliadam",
        "onıkıofkelıadam",
        "12ofkelıadam",
        "onıkıofkelıadam",
        "12angrymen",
        "twelweangrymen",
      ],
    ),
    Assignment(
      0,
      '28 Gün Sonra',
      'Assets/Images/Movies/28 Gün Sonra.jpg',
      [
        "28günsonra",
        "28gunsonra",
        "28dayslater",
        "yirmisekizgünsonra",
        "yırmisekizgünsonra",
        "yırmısekizgünsonra",
        "yırmısekızgünsonra",
        "yırmısekızgünsonra",
        "yırmısekızgunsonra",
        "twentyeightdayslater",
        "twentyeıghtdayslater",
      ],
    ),
    Assignment(
      0,
      'A Quiet Place',
      'Assets/Images/Movies/A Quiet Place.jpg',
      [
        "aquietplace",
        "aquıetplace",
        "sessizbiryer",
        "sessızbiryer",
        "sessızbıryer",
      ],
    ),
    Assignment(
      0,
      'A Star Is Born',
      'Assets/Images/Movies/A Star Is Born.jpg',
      [
        "astarısborn",
        "astarisborn",
        "starisborn",
        "starısborn",
        "biryildizdoğuyor",
        "biryıldizdoğuyor",
        "biryıldızdoğuyor",
        "bıryıldızdoguyor",
      ],
    ),
    Assignment(
      0,
      'A.R.O.G',
      'Assets/Images/Movies/A.R.O.G.jpg',
      [
        "arog",
        "a.r.o.g.",
        "a.r.o.g",
      ],
    ),
    Assignment(
      0,
      'Abluka',
      'Assets/Images/Movies/Abluka.jpg',
      [
        "abluka",
        "frenzy",
      ],
    ),
    Assignment(
      0,
      'Ahlat Ağacı',
      'Assets/Images/Movies/Ahlat Ağacı.jpg',
      [
        "ahlatağacı",
        "ahlatağaci",
        "ahlatagacı",
        "ahlatagaci",
        "thewildpeartree",
        "wildpeartree",
        "thewıldpeartree",
        "wıldpeartree",
      ],
    ),
    Assignment(
      0,
      'Aile Arasında',
      'Assets/Images/Movies/Aile Arasında.jpg',
      [
        "ailearasında",
        "ailearasinda",
        "aılearasında",
        "aılearasinda",
      ],
    ),
    Assignment(
      0,
      'Akıl Oyunları',
      'Assets/Images/Movies/Akıl Oyunları.jpg',
      [
        "akıloyunları",
        "akiloyunlari",
        "akıloyunlari",
        "abeautıfulmınd",
        "beautıfulmınd",
        "abeautifulmind",
        "beautifulmind",
      ],
    ),
    Assignment(
      0,
      'Amelie',
      'Assets/Images/Movies/Amelie.jpg',
      [
        "amelie",
        "amelıe",
      ],
    ),
    Assignment(
      0,
      'Ant-Man',
      'Assets/Images/Movies/Ant-Man.jpg',
      [
        "ant-man",
        "antman",
        "karıncaadam",
        "karincaadam",
      ],
    ),
    Assignment(
      0,
      'Aqua Man',
      'Assets/Images/Movies/Aqua Man.jpg',
      [
        "aquaman",
        "aqua-man",
      ],
    ),
    Assignment(
      0,
      'Arif V 216',
      'Assets/Images/Movies/Arif V 216.jpg',
      [
        "arifv216",
        "arifve216",
        "arıfv216",
        "arıfve216",
        "arifvikiyüzonaltı",
        "arifveikiyüzonaltı",
        "arıfvıkıyuzonaltı",
        "arıfvekıyuzonaltı",
        "216",
        "ikiyüzonaltı",
      ],
    ),
    Assignment(
      0,
      'Asfaltın Kralları',
      'Assets/Images/Movies/Asfaltın Kralları.jpg',
      [
        "asfaltınkralları",
        "asfaltinkrallari",
        "fordvferrari",
        "fordversusferrari",
        "fordvferrarı",
        "fordversusferrarı",
      ],
    ),
    Assignment(
      0,
      'Aslan Kral',
      'Assets/Images/Movies/Aslan Kral.jpg',
      [
        "aslankral",
        "thelionking",
        "thelionkıng",
        "thelıonkıng",
      ],
    ),
    Assignment(
      0,
      'Av Mevsimi',
      'Assets/Images/Movies/Av Mevsimi.jpg',
      [
        "avmevsimi",
        "avmevsımi",
        "avmevsımı",
        "avmevsimı",
      ],
    ),
    Assignment(
      0,
      'Avatar',
      'Assets/Images/Movies/Avatar.jpg',
      [
        "avatar",
      ],
    ),
    Assignment(
      0,
      'Ayla',
      'Assets/Images/Movies/Ayla.jpg',
      [
        "ayla",
        "thedaughterofwar",
        "daughterofwar",
      ],
    ),
    Assignment(
      0,
      'Babam ve Oğlum',
      'Assets/Images/Movies/Babam ve Oğlum.jpg',
      [
        "babamveoğlum",
        "babamoğlum",
        "babamveoglum",
        "babamoglum",
      ],
    ),
    Assignment(
      0,
      'Bal Ülkesi',
      'Assets/Images/Movies/Bal Ülkesi.jpg',
      [
        "balülkesi",
        "balulkesi",
        "balulkesı",
        "honeyland",
      ],
    ),
    Assignment(
      0,
      'Bana Masal Anlatma',
      'Assets/Images/Movies/Bana Masal Anlatma.jpg',
      [
        "banamasalanlatma",
        "masalanlatma",
      ],
    ),
    Assignment(
      0,
      'Banker Bilo',
      'Assets/Images/Movies/Banker Bilo.jpg',
      [
        "bankerbilo",
        "bankerbılo",
      ],
    ),
    Assignment(
      0,
      'Başlat',
      'Assets/Images/Movies/Başlat.jpg',
      [
        "başlat",
        "baslat",
        "readyplayerone",
        "playerone",
      ],
    ),
    Assignment(
      0,
      'Battal Gazi',
      'Assets/Images/Movies/Battal Gazi.jpg',
      [
        "battalgazi",
        "battalgazı",
      ],
    ),
    Assignment(
      0,
      'Ben Efsaneyim',
      'Assets/Images/Movies/Ben Efsaneyim.jpg',
      [
        "iamlegend",
        "ıamlegend",
        "benefsaneyim",
        "benefsaneyım",
      ],
    ),
    Assignment(
      0,
      "Bir Zamanlar Anadolu'da",
      'Assets/Images/Movies/Bir Zamanlar Anadoluda.jpg',
      [
        "birzamanlaranadolu'da",
        "bırzamanlaranadolu'da",
        "birzamanlaranadoluda",
        "bırzamanlaranadoluda",
        "onceuponatimeinanatolia",
        "onceuponatımeınanatolıa",
      ],
    ),
    Assignment(
      0,
      'Bird Box',
      'Assets/Images/Movies/Bird Box.jpg',
      [
        "birdbox",
        "bırdbox",
        "kuşkutusu",
        "kuskutusu",
      ],
    ),
    Assignment(
      0,
      'Bizim İçin Şampiyon',
      'Assets/Images/Movies/Bizim İçin Şampiyon.jpg',
      [
        "bizimiçinşampiyon",
        "bızimiçinşampiyon",
        "bızımiçinşampiyon",
        "bızımıçinşampiyon",
        "bızımıcinşampiyon",
        "bızımıcınşampiyon",
        "bızımıcınsampiyon",
        "bızımıcınsampıyon",
        "boldpilot",
        "boldpılot",
      ],
    ),
    Assignment(
      0,
      'Black Panther',
      'Assets/Images/Movies/Black Panther.jpg',
      [
        "blackpanther",
        "karapanter",
      ],
    ),
    Assignment(
      0,
      'BlacKkKlansman',
      'Assets/Images/Movies/BlacKkKlansman.jpg',
      [
        "blackkklansman",
        "blackklansman",
        "blacklansman",
        "karanlıklakarşıkarşıya",
        "karanliklakarşıkarşıya",
        "karanliklakarsıkarşıya",
        "karanliklakarsikarşıya",
        "karanliklakarsikarsiya",
      ],
    ),
    Assignment(
      0,
      'Bohemian Rhapsody',
      'Assets/Images/Movies/Bohemian Rhapsody.jpg',
      [
        "bohemianrhapsody",
        "bohemıanrhapsody",
        "rhapsody",
        "bohemian",
      ],
    ),
    Assignment(
      0,
      'Call Me by Your Name',
      'Assets/Images/Movies/Call Me by Your Name.jpg',
      [
        "beniadınlaçağır",
        "benıadınlaçağır",
        "benıadınlacağır",
        "benıadınlacagır",
        "benıadınlacagir",
        "benıadınlacagır",
        "callmebyyourname",
      ],
    ),
    Assignment(
      0,
      'Canım Kardeşim',
      'Assets/Images/Movies/Canım Kardeşim.jpg',
      [
        "canımkardeşim",
        "canimkardeşim",
        "canimkardesim",
        "canimkardesım",
        "canımkardesım",
      ],
    ),
    Assignment(
      0,
      'Captain America',
      'Assets/Images/Movies/Captain America.jpg',
      [
        "captainamerica",
        "captaınamerıca",
        "kaptanamerika",
        "kaptanamerıka",
        "firstavenger",
        "fırstavenger",
        "ilkyenilmez",
        "ılkyenılmez",
      ],
    ),
    Assignment(
      0,
      'Catch Me If You Can',
      'Assets/Images/Movies/Catch Me If You Can.jpg',
      [
        "sıkıysayakala",
        "sikıysayakala",
        "sikiysayakala",
        "catchmeıfyoucan",
        "catchmeifyoucan",
      ],
    ),
    Assignment(
      0,
      'Cennetin Çocukları',
      'Assets/Images/Movies/Cennetin Çocukları.jpg',
      [
        "cennetinçocukları",
        "cennetınçocukları",
        "cennetıncocukları",
        "cennetıncocuklari",
        "cennetıncocukları",
        "childrenofheaven",
        "chıldrenofheaven",
      ],
    ),
    Assignment(
      0,
      'Naim Süleymanoğlu',
      'Assets/Images/Movies/Cep Herkülü.jpg',
      [
        "naimsüleymanoğlu",
        "naımsüleymanoğlu",
        "naımsuleymanoğlu",
        "naımsuleymanoglu",
        "cepherkülü",
        "cepherkulü",
        "cepherkulu",
      ],
    ),
    Assignment(
      0,
      'Cesur Yürek',
      'Assets/Images/Movies/Cesur Yürek.jpg',
      [
        "cesuryürek",
        "cesuryurek",
        "braveheart",
      ],
    ),
    Assignment(
      0,
      'Cinayet Günlüğü',
      'Assets/Images/Movies/Cinayet Günlüğü.jpg',
      [
        "cinayetgünlüğü",
        "cınayetgünlüğü",
        "cınayetgunlüğü",
        "cınayetgunluğü",
        "cınayetgunlugü",
        "cınayetgunlugu",
        "memoriesofmurder",
        "memorıesofmurder",
      ],
    ),
    Assignment(
      0,
      'Cold War',
      'Assets/Images/Movies/Cold War.jpg',
      [
        "coldwar",
        "soğuksavaş",
        "soguksavaş",
        "soguksavas",
      ],
    ),
    Assignment(
      0,
      'Çizgi Pijamalı Çocuk',
      'Assets/Images/Movies/Çizgi Pijamalı Çocuk.jpg',
      [
        "çizgipijamalıçocuk",
        "çızgipijamalıçocuk",
        "çızgıpijamalıçocuk",
        "çızgıpıjamalıçocuk",
        "çızgıpıjamaliçocuk",
        "çızgıpıjamalicocuk",
        "çızgıpıjamalıcocuk",
        "theboyinthestripedpyjamas",
        "theboyınthestripedpyjamas",
        "boyınthestripedpyjamas",
        "boyinthestripedpyjamas",
      ],
    ),
    Assignment(
      0,
      'Çöpçüler Kralı',
      'Assets/Images/Movies/Çöpçüler Kralı.jpg',
      [
        "çöpçülerkralı",
        "cöpçülerkralı",
        "copçülerkralı",
        "copcülerkralı",
        "copculerkralı",
        "copculerkrali",
        "copculerkralı",
      ],
    ),
    Assignment(
      0,
      'Dağ',
      'Assets/Images/Movies/Dağ.jpg',
      [
        "dağ",
        "dag",
      ],
    ),
    Assignment(
      0,
      'Deadpool',
      'Assets/Images/Movies/Deadpool.jpg',
      [
        "deadpool",
      ],
    ),
    Assignment(
      0,
      'Devrim Arabaları',
      'Assets/Images/Movies/Devrim Arabaları.jpg',
      [
        "devrimarabaları",
        "devrımarabaları",
        "devrımarabalari",
      ],
    ),
    Assignment(
      0,
      'Doctor Strange',
      'Assets/Images/Movies/Doctor Strange.jpg',
      [
        "doctorstrange",
        "strange",
      ],
    ),
    Assignment(
      0,
      'Dünya Savaşı Z',
      'Assets/Images/Movies/Dünya Savaşı Z.jpg',
      [
        "dünyasavaşız",
        "dunyasavaşız",
        "dunyasavasız",
        "dunyasavasiz",
        "worldwarz",
        "z",
      ],
    ),
    Assignment(
      0,
      'Dünyalı',
      'Assets/Images/Movies/Dünyalı.jpg',
      [
        "dünyalı",
        "dunyalı",
        "dunyali",
        "manfromearth",
      ],
    ),
    Assignment(
      0,
      'Endgame',
      'Assets/Images/Movies/Endgame.jpg',
      [
        "endgame",
        "avengersendgame",
        "sonoyun",
        "yenilmezlersonoyun",
        "yenılmezlersonoyun",
      ],
    ),
    Assignment(
      0,
      "Er Ryan'ı Kurtarmak",
      "Assets/Images/Movies/Er Ryan'ı Kurtarmak.jpg",
      [
        "erryan'ıkurtarmak",
        "erryan'ikurtarmak",
        "erryanıkurtarmak",
        "erryanikurtarmak",
        "savingprivateryan",
        "savıngprıvateryan",
      ],
    ),
    Assignment(
      0,
      'Esaretin Bedeli',
      'Assets/Images/Movies/Esaretin Bedeli.jpg',
      [
        "esaretinbedeli",
        "esaretınbedeli",
        "esaretınbedelı",
        "theshawshankredemption",
        "theshawshankredemptıon",
        "shawshankredemption",
        "shawshankredemptıon",
      ],
    ),
    Assignment(
      0,
      'Eşkiya',
      'Assets/Images/Movies/Eşkiya.jpg',
      [
        "eşkiya",
        "eskiya",
        "eskıya",
      ],
    ),
    Assignment(
      0,
      'Evlilk Hikayesi',
      'Assets/Images/Movies/Evlilk Hikayesi.jpg',
      [
        "evlilikhikayesi",
        "evlılikhikayesi",
        "evlılıkhikayesi",
        "evlılıkhıkayesi",
        "evlılıkhıkayesı",
        "marriagestory",
        "marrıagestory",
      ],
    ),
    Assignment(
      0,
      'Fight Club',
      'Assets/Images/Movies/Fight Club.jpg',
      [
        "fightclub",
        "fıghtclub",
        "dövüşkulübü",
        "dovüşkulübü",
        "dovuşkulübü",
        "dovuskulübü",
        "dovuskulubü",
        "dovuskulubu",
      ],
    ),
    Assignment(
      0,
      'First Man',
      'Assets/Images/Movies/First Man.jpg',
      [
        "firstman",
        "fırstman",
        "ay'dailkinsan",
        "ay'daılkinsan",
        "ay'daılkınsan",
        "aydailkinsan",
        "aydaılkinsan",
        "aydaılkınsan",
        "ilkinsan",
        "ılkinsan",
        "ilkınsan",
        "ılkınsan",
      ],
    ),
    Assignment(
      0,
      'Forrest Gump',
      'Assets/Images/Movies/Forrest Gump.jpg',
      [
        "forrestgump",
        "forrest",
        "gump",
      ],
    ),
    Assignment(
      0,
      'G.O.R.A.',
      'Assets/Images/Movies/G.O.R.A..jpg',
      [
        "g.o.r.a.",
        "g.o.r.a",
        "gora",
      ],
    ),
    Assignment(
      0,
      'Geleceğe Dönüş',
      'Assets/Images/Movies/Geleceğe Dönüş.jpg',
      [
        "geleceğedönüş",
        "gelecegedönüş",
        "gelecegedonüş",
        "gelecegedonuş",
        "gelecegedonus",
        "backtothefuture",
        "bttf",
      ],
    ),
    Assignment(
      0,
      'Gladyatör',
      'Assets/Images/Movies/Gladyatör.jpg',
      [
        "gladyatör",
        "gladyator",
        "gladıator",
        "gladiator",
      ],
    ),
    Assignment(
      0,
      'Godfather',
      'Assets/Images/Movies/Godfather.jpg',
      [
        "godfather",
      ],
    ),
    Assignment(
      0,
      'Gönül Yarası',
      'Assets/Images/Movies/Gönül Yarası.jpg',
      [
        "gönülyarası",
        "gonülyarası",
        "gonulyarası",
        "gonulyarasi",
        "gonulyarası",
      ],
    ),
    Assignment(
      0,
      'Galaksinin Koruyucuları',
      'Assets/Images/Movies/Guardians of the Galaxy.jpg',
      [
        "guardiansofthegalaxy",
        "guardıansofthegalaxy",
        "galaksininkoruyucuları",
        "galaksıninkoruyucuları",
        "galaksınınkoruyucuları",
        "galaksınınkoruyuculari",
      ],
    ),
    Assignment(
      0,
      'Gün Batmadan',
      'Assets/Images/Movies/Gün Batmadan.jpg',
      [
        "günbatmadan",
        "gunbatmadan",
        "beforesunset",
      ],
    ),
    Assignment(
      0,
      'Güneşi Gördüm',
      'Assets/Images/Movies/Güneşi Gördüm.jpg',
      [
        "güneşigördüm",
        "guneşigördüm",
        "gunesigördüm",
        "gunesıgördüm",
        "gunesıgordüm",
        "gunesıgordum",
      ],
    ),
    Assignment(
      0,
      'Hababam Sınıfı',
      'Assets/Images/Movies/Hababam Sınıfı.jpg',
      [
        "hababamsınıfı",
        "hababamsinıfı",
        "hababamsınıfi",
        "hababamsinifi",
      ],
    ),
    Assignment(
      0,
      'Hamılton',
      'Assets/Images/Movies/Hamılton.jpg',
      [
        "hamılton",
        "hamilton",
      ],
    ),
    Assignment(
      0,
      'Harry Potter',
      'Assets/Images/Movies/Harry Potter.jpg',
      [
        "harrypotter",
        "harry",
        "distimitria",
        "dıstımıtrıa",
      ],
    ),
    Assignment(
      0,
      'Hayallerin Peşinde',
      'Assets/Images/Movies/Hayallerin Peşinde.jpg',
      [
        "hayallerinpeşinde",
        "hayallerınpeşinde",
        "hayallerınpesinde",
        "hayallerınpesınde",
        "revolutionaryroad",
        "revolutıonaryroad",
      ],
    ),
    Assignment(
      0,
      'Hayat Güzeldir',
      'Assets/Images/Movies/Hayat Güzeldir.jpg',
      [
        "hayatgüzeldir",
        "hayatguzeldir",
        "hayatguzeldır",
        "lifeisbeautiful",
        "lıfeısbeautıful",
      ],
    ),
    Assignment(
      0,
      'Hell or High Water',
      'Assets/Images/Movies/Hell or High Water.jpg',
      [
        "hellorhighwater",
        "hellorhıghwater",
        "comancheria",
        "comancherıa",
        "ikielikanda",
        "ıkielikanda",
        "ıkıelikanda",
        "ıkıelıkanda",
      ],
    ),
    Assignment(
      0,
      'Her Çocuk Özeldir',
      'Assets/Images/Movies/Her Çocuk Özeldir.jpg',
      [
        "herçocuközeldir",
        "hercocuközeldir",
        "hercocukozeldir",
        "hercocukozeldır",
        "yerdekiyıldızlar",
        "yerdekıyıldızlar",
        "yerdekıyildızlar",
        "yerdekıyildizlar",
        "yerdekıyıldızlar",
        "everychildisspecial",
        "everychıldısspecıal",
        "taarezameenpar",
      ],
    ),
    Assignment(
      0,
      'Hızlı ve Öfkeli',
      'Assets/Images/Movies/Hızlı ve Öfkeli.jpg',
      [
        "hızlıveöfkeli",
        "hizlıveöfkeli",
        "hizliveöfkeli",
        "hizliveofkeli",
        "hizliveofkelı",
        "hızlıveofkelı",
        "thefastandthefurious",
        "fastandfurious",
        "fastandthefurious",
        "thefastandthefurıous",
        "fastandthefurıous",
        "fastandfurıous",
      ],
    ),
    Assignment(
      0,
      'Hokkabaz',
      'Assets/Images/Movies/Hokkabaz.jpg',
      [
        "hokkabaz",
      ],
    ),
    Assignment(
      0,
      'I, Tonya',
      'Assets/Images/Movies/I, Tonya.jpg',
      [
        "ı,tonya",
        "ıam,tonya",
        "iamtonya",
        "ıtonya",
        "tonya",
      ],
    ),
    Assignment(
      0,
      'Inception',
      'Assets/Images/Movies/Inception.jpg',
      [
        "inception",
        "ınception",
        "ınceptıon",
        "başlangıç",
        "baslangıç",
        "baslangiç",
        "baslangic",
      ],
    ),
    Assignment(
      0,
      'İncir Reçeli',
      'Assets/Images/Movies/İncir Reçeli.jpg',
      [
        "incirreçeli",
        "ıncirreçeli",
        "ıncırreçeli",
        "ıncırreceli",
        "ıncırrecelı",
      ],
    ),
    Assignment(
      0,
      'The Platform',
      'Assets/Images/Movies/The Platform.jpg',
      [
        "theplatform",
        "platform",
      ],
    ),
    Assignment(
      0,
      'Incredible Hulk',
      'Assets/Images/Movies/Incredible Hulk.jpg',
      [
        "ıncrediblehulk",
        "ıncredıblehulk",
        "incrediblehulk",
        "hulk",
        "inanılmazhulk",
        "inanilmazhulk",
      ],
    ),
    Assignment(
      0,
      'İnek Şaban',
      'Assets/Images/Movies/İnek Şaban.jpg',
      [
        "inekşaban",
        "ınekşaban",
        "ıneksaban",
      ],
    ),
    Assignment(
      0,
      'Yıldızlar Arası',
      'Assets/Images/Movies/Interstellar.jpg',
      [
        "yıldızlararası",
        "yildızlararası",
        "yildizlararası",
        "yildizlararasi",
        "interstellar",
        "ınterstellar",
      ],
    ),
    Assignment(
      0,
      'Can Dostum',
      'Assets/Images/Movies/Intouchables.jpg',
      [
        "ıntouchables",
        "intouchables",
        "candostum",
      ],
    ),
    Assignment(
      0,
      'Iron Man',
      'Assets/Images/Movies/Iron Man.jpg',
      [
        "ıronman",
        "ironman",
      ],
    ),
    Assignment(
      0,
      'Isle of Dogs',
      'Assets/Images/Movies/Isle of Dogs.jpg',
      [
        "ısleofdogs",
        "isleofdogs",
        "köpekadası",
        "kopekadası",
        "kopekadasi",
      ],
    ),
    Assignment(
      0,
      'Issız Adam',
      'Assets/Images/Movies/Issız Adam.jpg',
      [
        "ıssızadam",
        "ıssizadam",
        "issizadam",
      ],
    ),
    Assignment(
      0,
      'İtirazım Var',
      'Assets/Images/Movies/İtirazım Var.jpg',
      [
        "itirazımvar",
        "ıtirazımvar",
        "ıtırazımvar",
        "ıtırazimvar",
        "ıtırazımvar",
      ],
    ),
    Assignment(
      0,
      'İyi Kötü ve Çirkin',
      'Assets/Images/Movies/İyi Kötü ve Çirkin.jpg',
      [
        "iyikötüveçirkin",
        "ıyikötüveçirkin",
        "ıyıkötüveçirkin",
        "ıyıkotüveçirkin",
        "ıyıkotuveçirkin",
        "ıyıkotuvecirkin",
        "ıyıkotuvecırkin",
        "ıyıkotuvecırkın",
        "iyikötüçirkin",
        "ıyikötüçirkin",
        "ıyıkötüçirkin",
        "ıyıkotüçirkin",
        "ıyıkotuçirkin",
        "ıyıkotucirkin",
        "ıyıkotucırkin",
        "ıyıkotucırkın",
        "goodbadugly",
        "thegoodthebadtheugly",
      ],
    ),
    Assignment(
      0,
      'Joker',
      'Assets/Images/Movies/Joker.jpg',
      [
        "joker",
      ],
    ),
    Assignment(
      0,
      'Jurrasic Park',
      'Assets/Images/Movies/Jurrasic Park.jpg',
      [
        "jurrasicpark",
        "jurrasıcpark",
      ],
    ),
    Assignment(
      0,
      'Kabadayı',
      'Assets/Images/Movies/Kabadayı.jpg',
      [
        "kabadayı",
        "kabadayi",
      ],
    ),
    Assignment(
      0,
      'Kaçamak',
      'Assets/Images/Movies/Kaçamak.jpg',
      [
        "kaçamak",
        "kacamak",
        "karakomikfilmler",
        "karakomıkfilmler",
        "karakomıkfılmler",
      ],
    ),
    Assignment(
      0,
      'Kader',
      'Assets/Images/Movies/Kader.jpg',
      [
        "kader",
      ],
    ),
    Assignment(
      0,
      'Kapıcılar Kralı',
      'Assets/Images/Movies/Kapıcılar Kralı.jpg',
      [
        "kapıcılarkralı",
        "kapicılarkralı",
        "kapicilarkralı",
        "kapicilarkrali",
      ],
    ),
    Assignment(
      0,
      'Kar Küreyici',
      'Assets/Images/Movies/Kar Küreyici.jpg',
      [
        "karküreyici",
        "karkureyici",
        "karkureyıci",
        "karkureyıcı",
        "snowpıercer",
        "snowpiercer",
      ],
    ),
    Assignment(
      0,
      'Karayip Korsanları',
      'Assets/Images/Movies/Karayip Korsanları.jpg',
      [
        "karayipkorsanları",
        "karayıpkorsanları",
        "karayıpkorsanlari",
        "piratesofthecarribean",
        "pıratesofthecarribean",
        "pıratesofthecarrıbean",
        "piratesofcarribean",
        "pıratesofcarribean",
        "pıratesofcarrıbean",
      ],
    ),
    Assignment(
      0,
      'Kaybedenler Kulübü',
      'Assets/Images/Movies/Kaybedenler Kulübü.jpg',
      [
        "kaybedenlerkulübü",
        "kaybedenlerkulubü",
        "kaybedenlerkulubu",
      ],
    ),
    Assignment(
      0,
      'Kayıp Balık Nemo',
      'Assets/Images/Movies/Kayıp Balık Nemo.jpg',
      [
        "kayıpbalıknemo",
        "kayipbalıknemo",
        "kayipbaliknemo",
        "nemo",
      ],
    ),
    Assignment(
      0,
      'Kefaret',
      'Assets/Images/Movies/Kefaret.jpg',
      [
        "kefaret",
        "atonement",
      ],
    ),
    Assignment(
      0,
      'Kelebeğin Rüyası',
      'Assets/Images/Movies/Kelebeğin Rüyası.jpg',
      [
        "kelebeğinrüyası",
        "kelebeginrüyası",
        "kelebegınrüyası",
        "kelebegınruyası",
        "kelebegınruyasi",
      ],
    ),
    Assignment(
      0,
      'Kelebek Etkisi',
      'Assets/Images/Movies/Kelebek Etkisi.jpg',
      [
        "kelebeketkisi",
        "kelebeketkısi",
        "kelebeketkisı",
        "kelebeketkısı",
        "thebutterflyeffect",
        "butterflyeffect",
      ],
    ),
    Assignment(
      0,
      'Kış Uykusu',
      'Assets/Images/Movies/Kış Uykusu.jpg',
      [
        "kışuykusu",
        "kişuykusu",
        "kisuykusu",
        "kısuykusu",
        "wintersleep",
        "wıntersleep",
      ],
    ),
    Assignment(
      0,
      'Köstebek',
      'Assets/Images/Movies/Köstebek.jpg',
      [
        "köstebek",
        "kostebek",
        "thedeparted",
        "departed",
      ],
    ),
    Assignment(
      0,
      'Kuzuların Sessizliği',
      'Assets/Images/Movies/Kuzuların Sessizliği.jpg',
      [
        "kuzularınsessizliği",
        "kuzularinsessizliği",
        "kuzularinsessızliği",
        "kuzularinsessızlıği",
        "kuzularinsessızlıgi",
        "kuzularinsessızlıgı",
        "kuzularınsessızlıgı",
        "thesilenceofthelambs",
        "thesılenceofthelambs",
        "silenceofthelambs",
        "sılenceofthelambs",
      ],
    ),
    Assignment(
      0,
      'Limonata',
      'Assets/Images/Movies/Limonata.jpg',
      [
        "limonata",
        "lımonata",
      ],
    ),
    Assignment(
      0,
      'Logan',
      'Assets/Images/Movies/Logan.jpg',
      [
        "logan",
        "wolverine",
        "wolverıne",
        "wolverin",
        "wolverın",
      ],
    ),
    Assignment(
      0,
      'Masumiyet',
      'Assets/Images/Movies/Masumiyet.jpg',
      [
        "masumiyet",
        "masumıyet",
        "ınnocence",
        "innocence",
      ],
    ),
    Assignment(
      0,
      'Matrix',
      'Assets/Images/Movies/Matrix.jpg',
      [
        "matrix",
        "matrıx",
        "redpill",
        "redpillorbluepill",
        "redpillorbluepıll",
        "redpıllorbluepill",
        "redpıllorbluepıll",
        "bluepill",
      ],
    ),
    Assignment(
      0,
      'Maymunlar Cehennemi',
      'Assets/Images/Movies/Maymunlar Cehennemi.jpg',
      [
        "maymunlarcehennemi",
        "maymunlarcehennemı",
        "riseoftheplanetoftheapes",
        "rıseoftheplanetoftheapes",
      ],
    ),
    Assignment(
      0,
      "Molly's Game",
      "Assets/Images/Movies/Molly's Game.jpg",
      [
        "molly'sgame",
        "mollysgame",
        "mollygame",
        "molly'ninoyunu",
        "molly'nınoyunu",
        "mollyninoyunu",
        "mollynınoyunu",
        "molly",
      ],
    ),
    Assignment(
      0,
      'Mucize',
      'Assets/Images/Movies/Mucize.jpg',
      [
        "mucize",
        "mucıze",
      ],
    ),
    Assignment(
      0,
      'Mustang',
      'Assets/Images/Movies/Mustang.jpg',
      [
        "mustang",
      ],
    ),
    Assignment(
      0,
      'Müslüm',
      'Assets/Images/Movies/Müslüm.jpg',
      [
        "müslüm",
        "muslüm",
        "müslum",
        "muslum",
      ],
    ),
    Assignment(
      0,
      'Nefes Vatan Sağolsun',
      'Assets/Images/Movies/Nefes Vatan Sağolsun.jpg',
      [
        "nefesvatansağolsun",
        "nefesvatansagolsun",
        "nefes",
        "vatansağolsun",
        "vatansagolsun",
      ],
    ),
    Assignment(
      0,
      'Organize İşler',
      'Assets/Images/Movies/Organize İşler.jpg',
      [
        "organizeişler",
        "organızeişler",
        "organızeışler",
        "organızeısler",
      ],
    ),
    Assignment(
      0,
      'Oyuncak Hikayesi',
      'Assets/Images/Movies/Oyuncak Hikayesi.jpg',
      [
        "oyuncakhikayesi",
        "oyuncakhıkayesi",
        "oyuncakhikayesı",
        "oyuncakhıkayesı",
        "toystory",
      ],
    ),
    Assignment(
      0,
      'Ölüm Takibi',
      'Assets/Images/Movies/Ölüm Takibi.jpg',
      [
        "ölümtakibi",
        "olümtakibi",
        "olumtakibi",
        "olumtakıbi",
        "olumtakıbı",
        "bladerunner",
        "runner",
        "blade",
      ],
    ),
    Assignment(
      0,
      'Ölümcül Deney',
      'Assets/Images/Movies/Ölümcül Deney.jpg',
      [
        "ölümcüldeney",
        "olümcüldeney",
        "olumcüldeney",
        "olumculdeney",
        "residentevil",
        "resıdentevil",
        "resıdentevıl",
      ],
    ),
    Assignment(
      0,
      'Ölümlü Dünya',
      'Assets/Images/Movies/Ölümlü Dünya.jpg',
      [
        "ölümlüdünya",
        "olümlüdünya",
        "olumlüdünya",
        "olumludünya",
        "olumludunya",
      ],
    ),
    Assignment(
      0,
      'Para Avcısı',
      'Assets/Images/Movies/Para Avcısı.jpg',
      [
        "paraavcısı",
        "paraavcisı",
        "paraavcısi",
        "paraavcısı",
        "thewolfofwallstreet",
        "wolfofwallstreet",
        "wallstreet",
      ],
    ),
    Assignment(
      0,
      'Parazit',
      'Assets/Images/Movies/Parazit.jpg',
      [
        "parazit",
        "parazıt",
        "parasite",
        "parasıte",
      ],
    ),
    Assignment(
      0,
      'Pardon',
      'Assets/Images/Movies/Pardon.jpg',
      [
        "pardon",
      ],
    ),
    Assignment(
      0,
      'Pek Yakında',
      'Assets/Images/Movies/Pek Yakında.jpg',
      [
        "pekyakında",
        "pekyakinda",
      ],
    ),
    Assignment(
      0,
      "Pi'nin Yaşamı",
      "Assets/Images/Movies/Pi'nin Yaşamı.jpg",
      [
        "pi'ninyaşamı",
        "pı'ninyaşamı",
        "pı'nınyaşamı",
        "pı'nınyasamı",
        "pı'nınyasami",
        "pininyaşamı",
        "pıninyaşamı",
        "pınınyaşamı",
        "pınınyasamı",
        "pınınyasami",
        "lifeofpi",
        "lıfeofpi",
        "lıfeofpı",
      ],
    ),
    Assignment(
      0,
      'Piyanist',
      'Assets/Images/Movies/Piyanist.jpg',
      [
        "piyanist",
        "pıyanist",
        "pıyanıst",
        "thepianist",
        "thepıanist",
        "thepıanıst",
        "pianist",
        "pıanist",
        "pıanıst",
      ],
    ),
    Assignment(
      0,
      'Prestij',
      'Assets/Images/Movies/Prestij.jpg',
      [
        "prestij",
        "prestıj",
        "theprestige",
        "theprestıge",
        "prestige",
        "prestıge",
      ],
    ),
    Assignment(
      0,
      'Recep İvedik',
      'Assets/Images/Movies/Recep İvedik.jpg',
      [
        "recepivedik",
        "recepıvedik",
        "recepıvedık",
      ],
    ),
    Assignment(
      0,
      'Requiem For a Dream',
      'Assets/Images/Movies/Requiem For a Dream.jpg',
      [
        "requiemforadream",
        "requıemforadream",
        "birrüyaiçinağıt",
        "bırrüyaiçinağıt",
        "bırruyaiçinağıt",
        "bırruyaıçinağıt",
        "bırruyaıcinağıt",
        "bırruyaıcınağıt",
        "bırruyaıcınagıt",
        "bırruyaıcınagit",
        "rüyaiçinağıt",
        "ruyaiçinağıt",
        "ruyaıçinağıt",
        "ruyaıcinağıt",
        "ruyaıcınağıt",
        "ruyaıcınagıt",
        "ruyaıcınagit",
      ],
    ),
    Assignment(
      0,
      'Roma',
      'Assets/Images/Movies/Roma.jpg',
      [
        "roma",
      ],
    ),
    Assignment(
      0,
      'Room',
      'Assets/Images/Movies/Room.jpg',
      [
        "gizlidünya",
        "gızlidünya",
        "gızlıdünya",
        "gızlıdunya",
        "room",
        "oda",
      ],
    ),
    Assignment(
      0,
      'Salgın',
      'Assets/Images/Movies/Salgın.jpg',
      [
        "salgın",
        "salgin",
        "contagion",
        "contagıon",
      ],
    ),
    Assignment(
      0,
      'Sarmaşık',
      'Assets/Images/Movies/Sarmaşık.jpg',
      [
        "sarmaşık",
        "sarmasık",
        "sarmasik",
      ],
    ),
    Assignment(
      0,
      "Schindler'in Listesi",
      "Assets/Images/Movies/Schindler'in Listesi.jpg",
      [
        "schindler'inlistesi",
        "schındler'inlistesi",
        "schındler'ınlistesi",
        "schındler'ınlıstesi",
        "schındler'ınlıstesı",
        "schindlerinlistesi",
        "schındlerinlistesi",
        "schındlerınlistesi",
        "schındlerınlıstesi",
        "schındlerınlıstesı",
        "schindler'slist",
        "schındler'slist",
        "schındler'slıst",
      ],
    ),
    Assignment(
      0,
      'Searching',
      'Assets/Images/Movies/Searching.jpg',
      [
        "searching",
        "searchıng",
        "aranıyor",
        "araniyor",
        "kayıparanıyor",
        "kayiparanıyor",
        "kayiparaniyor",
      ],
    ),
    Assignment(
      0,
      'Selvi Boylum Al Yazmalım',
      'Assets/Images/Movies/Selvi Boylum Al Yazmalım.jpg',
      [
        "selviboylumalyazmalım",
        "selvıboylumalyazmalım",
        "selvıboylumalyazmalim",
      ],
    ),
    Assignment(
      0,
      'Sen Aydınlatırsın Geceyi',
      'Assets/Images/Movies/Sen Aydınlatırsın Geceyi.jpg',
      [
        "senaydınlatırsıngeceyi",
        "senaydinlatırsıngeceyi",
        "senaydinlatirsıngeceyi",
        "senaydinlatirsingeceyi",
        "senaydinlatirsingeceyi",
        "senaydinlatirsingeceyı",
        "senaydınlatırsıngeceyı",
      ],
    ),
    Assignment(
      0,
      'Sıkı Dostlar',
      'Assets/Images/Movies/Sıkı Dostlar.jpg',
      [
        "sıkıdostlar",
        "sıkidostlar",
        "sikidostlar",
        "goodfellas",
        "fellas",
      ],
    ),
    Assignment(
      0,
      'Sil Baştan',
      'Assets/Images/Movies/Sil Baştan.jpg',
      [
        "silbaştan",
        "silbastan",
        "sılbastan",
        "eternalsunshineofthespotlessmind",
        "eternalsunshıneofthespotlessmind",
        "eternalsunshıneofthespotlessmınd",
      ],
    ),
    Assignment(
      0,
      'Sonbahar',
      'Assets/Images/Movies/Sonbahar.jpg',
      [
        "sonbahar",
        "herbst",
      ],
    ),
    Assignment(
      0,
      'Soysuzlar Çetesi',
      'Assets/Images/Movies/Soysuzlar Çetesi.jpg',
      [
        "soysuzlarçetesi",
        "soysuzlarcetesi",
        "soysuzlarcetesı",
        "inglouriousbasterds",
        "ınglouriousbasterds",
        "ınglourıousbasterds",
      ],
    ),
    Assignment(
      0,
      'Spider Man',
      'Assets/Images/Movies/Spider Man.jpg',
      [
        "spiderman",
        "spıderman",
        "spider-man",
        "spıder-man",
        "örümcekadam",
        "orümcekadam",
        "orumcekadam",
      ],
    ),
    Assignment(
      0,
      'Star Wars',
      'Assets/Images/Movies/Star Wars.jpg',
      [
        "starwars",
        "yıldızsavaşları",
        "yildızsavaşları",
        "yildizsavaşları",
        "yildizsavasları",
        "yildizsavaslari",
        "yıldızsavasları",
      ],
    ),
    Assignment(
      0,
      'Super Man',
      'Assets/Images/Movies/Super Man.jpg',
      [
        "superman",
        "super",
      ],
    ),
    Assignment(
      0,
      'Süt Kardeşler',
      'Assets/Images/Movies/Süt Kardeşler.jpg',
      [
        "sütkardeşler",
        "sutkardeşler",
        "sutkardesler",
      ],
    ),
    Assignment(
      0,
      'Tarkan',
      'Assets/Images/Movies/Tarkan.jpg',
      [
        "tarkan",
      ],
    ),
    Assignment(
      0,
      'Taxi',
      'Assets/Images/Movies/Taxi.jpg',
      [
        "taxi",
        "taxı",
        "taksi",
        "taksı",
      ],
    ),
    Assignment(
      0,
      'Terminatör',
      'Assets/Images/Movies/Terminatör.jpg',
      [
        "terminatör",
        "termınatör",
        "termınator",
        "terminator",
      ],
    ),
    Assignment(
      0,
      'Testere',
      'Assets/Images/Movies/Testere.jpg',
      [
        "testere",
        "saw",
        "jigsaw",
      ],
    ),
    Assignment(
      0,
      'Elektrik Savaşları',
      'Assets/Images/Movies/The Current War.jpg',
      [
        "thecurrentwar",
        "currentwar",
        "elektriksavaşları",
        "elektrıksavaşları",
        "elektrıksavasları",
        "elektriksavaslari",
        "akımsavaşları",
        "akimsavaşları",
        "akimsavasları",
        "akimsavaslari",
        "acvsdc",
      ],
    ),
    Assignment(
      0,
      'Kara Şövalye',
      'Assets/Images/Movies/The Dark Night.jpg',
      [
        "thedarknight",
        "thedarknıght",
        "darknight",
        "darknıght",
        "karaşövalye",
        "karasövalye",
        "karasovalye",
      ],
    ),
    Assignment(
      0,
      'Cehennem Melekleri',
      'Assets/Images/Movies/The Expendables.jpg',
      [
        "theexpendables",
        "expendables",
        "cehennemmelekleri",
        "cehennemmeleklerı",
      ],
    ),
    Assignment(
      0,
      'The Great Hack',
      'Assets/Images/Movies/The Great Hack.jpg',
      [
        "thegreathack",
        "greathack",
        "hack",
      ],
    ),
    Assignment(
      0,
      'Enigma',
      'Assets/Images/Movies/The Imitation Game.jpg',
      [
        "theimitationgame",
        "theımitationgame",
        "theımıtationgame",
        "theımıtatıongame",
        "imitationgame",
        "ımitationgame",
        "ımıtationgame",
        "ımıtatıongame",
        "enigma",
        "enıgma",
      ],
    ),
    Assignment(
      0,
      'Thor',
      'Assets/Images/Movies/Thor.jpg',
      [
        "thor",
      ],
    ),
    Assignment(
      0,
      'Titanic',
      'Assets/Images/Movies/Titanic.jpg',
      [
        "titanic",
        "tıtanic",
        "tıtanıc",
      ],
    ),
    Assignment(
      0,
      'Tosun Paşa',
      'Assets/Images/Movies/Tosun Paşa.jpg',
      [
        "tosunpaşa",
        "tosunpasa",
      ],
    ),
    Assignment(
      0,
      'Tron',
      'Assets/Images/Movies/Tron.jpg',
      [
        "tron",
      ],
    ),
    Assignment(
      0,
      'Truman Show',
      'Assets/Images/Movies/Truman Show.jpg',
      [
        "trumanshow",
        "thetrumanshow",
      ],
    ),
    Assignment(
      0,
      'Upgrade',
      'Assets/Images/Movies/Upgrade.jpg',
      [
        "upgrade",
        "yükselt",
        "yukselt",
        "yükseltme",
        "yukseltme",
      ],
    ),
    Assignment(
      0,
      'Uzak',
      'Assets/Images/Movies/Uzak.jpg',
      [
        "uzak",
      ],
    ),
    Assignment(
      0,
      'Üç Maymun',
      'Assets/Images/Movies/Üç Maymun.jpg',
      [
        "üçmaymun",
        "ucmaymun",
        "3maymun",
      ],
    ),
    Assignment(
      0,
      'V for Vendetta',
      'Assets/Images/Movies/V for Vendetta.jpg',
      [
        "vforvendetta",
        "vendetta",
      ],
    ),
    Assignment(
      0,
      'Vizontele',
      'Assets/Images/Movies/Vizontele.jpg',
      [
        "vizontele",
        "vızontele",
      ],
    ),
    Assignment(
      0,
      'Savaş Atı',
      'Assets/Images/Movies/War Horse.jpg',
      [
        "warhorse",
        "savaşatı",
        "savasati",
        "savasatı",
      ],
    ),
    Assignment(
      0,
      'Kardaki İzler',
      'Assets/Images/Movies/Wind River.jpg',
      [
        "windriver",
        "wındriver",
        "windrıver",
        "wındrıver",
        "kardakiizler",
        "kardakıizler",
        "kardakiızler",
        "kardakıızler",
      ],
    ),
    Assignment(
      0,
      'Yahşi Batı',
      'Assets/Images/Movies/Yahşi Batı.jpg',
      [
        "yahşibatı",
        "yahsibatı",
        "yahsıbati",
        "yahsıbatı",
      ],
    ),
    Assignment(
      0,
      'Yeşil Yol',
      'Assets/Images/Movies/Yeşil Yol.jpg',
      [
        "yeşilyol",
        "yesilyol",
        "yesılyol",
        "thegreenmile",
        "thegreenmıle",
        "greenmile",
        "greenmıle",
      ],
    ),
    Assignment(
      0,
      'Yıldızlara Doğru',
      'Assets/Images/Movies/Yıldızlara Doğru.jpg',
      [
        "yıldızlaradoğru",
        "yildızlaradoğru",
        "yildizlaradoğru",
        "yildizlaradogru",
        "yıldızlaradogru",
        "adastra",
      ],
    ),
    Assignment(
      0,
      'Yok Oluş',
      'Assets/Images/Movies/Yok Oluş.jpg',
      [
        "yokoluş",
        "yokolus",
        "annihilation",
        "annıhilation",
        "annıhılation",
        "annıhılatıon",
      ],
    ),
    Assignment(
      0,
      'Yol',
      'Assets/Images/Movies/Yol.jpg',
      [
        "yol",
      ],
    ),
    Assignment(
      0,
      'Yüzüklerin Efendisi',
      'Assets/Images/Movies/Yüzüklerin Efendisi.jpg',
      [
        "yüzüklerinefendisi",
        "yuzüklerinefendisi",
        "yuzuklerinefendisi",
        "yuzuklerınefendisi",
        "yuzuklerınefendısi",
        "yuzuklerınefendısı",
        "thelordoftherings",
        "thelordoftherıngs",
        "lordoftherings",
        "lordoftherıngs",
        "lotr",
      ],
    ),
    Assignment(
      0,
      'Zamana Karşı',
      'Assets/Images/Movies/Zamana Karşı.jpg',
      [
        "zamanakarşı",
        "zamanakarsı",
        "zamanakarsi",
        "intime",
        "ıntime",
        "intıme",
        "ıntıme",
      ],
    ),
  ],
  [
    //dizi
    //Assignment(1, name, imagePath, keyWords),
    Assignment(
      1,
      '11.22.63',
      'Assets/Images/Series/11.22.63.jpg',
      [
        "11.22.63",
        "1122.63",
        "112263",
      ],
    ),
    Assignment(
      1,
      'After Life',
      'Assets/Images/Series/After Life.jpg',
      [
        "afterlife",
        "afterlıfe",
      ],
    ),
    Assignment(
      1,
      'Anne With an E',
      'Assets/Images/Series/Anne With an E.jpg',
      [
        "annewithane",
        "annewıthane",
      ],
    ),
    Assignment(
      1,
      'Arrow',
      'Assets/Images/Series/Arrow.jpg',
      [
        "arrow",
      ],
    ),
    Assignment(
      1,
      'Avatar Son Hava Bükücü',
      'Assets/Images/Series/Avatar Son Hava Bükücü.jpg',
      [
        "avatarsonhavabükücü",
        "avatarsonhavabukücü",
        "avatarsonhavabukucü",
        "avatarsonhavabukucu",
        "sonhavabükücü",
        "sonhavabukücü",
        "sonhavabukucü",
        "sonhavabukucu",
        "avatar",
      ],
    ),
    Assignment(
      1,
      'Band of Brothers',
      'Assets/Images/Series/Band of Brothers.jpg',
      [
        "bandofbrothers",
        "bandbrothers",
      ],
    ),
    Assignment(
      1,
      'Behzat Ç',
      'Assets/Images/Series/Behzat Ç.jpg',
      [
        "behzatç",
        "behzatc",
      ],
    ),
    Assignment(
      1,
      'Better Call Saul',
      'Assets/Images/Series/Better Call Saul.jpg',
      [
        "bettercallsaul",
      ],
    ),
    Assignment(
      1,
      'Black Mirror',
      'Assets/Images/Series/Black Mirror.jpg',
      [
        "blackmirror",
        "blackmırror",
      ],
    ),
    Assignment(
      1,
      'Breaking Bad',
      'Assets/Images/Series/Breaking Bad.jpg',
      [
        "breakingbad",
        "breakıngbad",
        "saymyname",
        "1483369",
      ],
    ),
    Assignment(
      1,
      'Brooklyn 99',
      'Assets/Images/Series/Brooklyn 99.jpg',
      [
        "brooklyn99",
        "brooklynninenine",
        "brooklynnınenine",
        "brooklynninenıne",
        "brooklynnınenıne",
      ],
    ),
    Assignment(
      1,
      'Community',
      'Assets/Images/Series/Community.jpg',
      [
        "community",
        "communıty",
      ],
    ),
    Assignment(
      1,
      'Çernobil',
      'Assets/Images/Series/Çernobil.jpg',
      [
        "çernobil",
        "cernobil",
        "cernobıl",
        "chernobyl",
      ],
    ),
    Assignment(
      1,
      'Daredevil',
      'Assets/Images/Series/Daredevil.jpg',
      [
        "daredevil",
        "daredevıl",
      ],
    ),
    Assignment(
      1,
      'Dark',
      'Assets/Images/Series/Dark.jpg',
      [
        "dark",
      ],
    ),
    Assignment(
      1,
      'Death Note',
      'Assets/Images/Series/Death Note.jpg',
      [
        "deathnote",
      ],
    ),
    Assignment(
      1,
      'Dexter',
      'Assets/Images/Series/Dexter.jpg',
      [
        "dexter",
      ],
    ),
    Assignment(
      1,
      'Doctor Who',
      'Assets/Images/Series/Doctor Who.jpg',
      [
        "doctorwho",
      ],
    ),
    Assignment(
      1,
      'Elite',
      'Assets/Images/Series/Elite.jpg',
      [
        "elite",
        "elıte",
      ],
    ),
    Assignment(
      1,
      'Ezel',
      'Assets/Images/Series/Ezel.jpg',
      [
        "ezel",
      ],
    ),
    Assignment(
      1,
      'Fargo',
      'Assets/Images/Series/Fargo.jpg',
      [
        "fargo",
      ],
    ),
    Assignment(
      1,
      'Friends',
      'Assets/Images/Series/Friends.jpg',
      [
        "friends",
        "frıends",
      ],
    ),
    Assignment(
      1,
      'Fringe',
      'Assets/Images/Series/Fringe.jpg',
      [
        "fringe",
        "frınge",
      ],
    ),
    Assignment(
      1,
      'Game of Thrones',
      'Assets/Images/Series/Game of Thrones.jpg',
      [
        "gameofthrones",
      ],
    ),
    Assignment(
      1,
      'Hannibal',
      'Assets/Images/Series/Hannibal.jpg',
      [
        "hannibal",
        "hannıbal",
      ],
    ),
    Assignment(
      1,
      'House of Cards',
      'Assets/Images/Series/House of Cards.jpg',
      [
        "houseofcards",
        "housecards",
      ],
    ),
    Assignment(
      1,
      'House',
      'Assets/Images/Series/House.jpg',
      [
        "house",
        "doctorhouse",
        "doctor",
      ],
    ),
    Assignment(
      1,
      'How I Met Your Mother',
      'Assets/Images/Series/How I Met Your Mother.jpg',
      [
        "howımetyourmother",
        "howimetyourmother",
      ],
    ),
    Assignment(
      1,
      'Kurtlar Vadisi',
      'Assets/Images/Series/Kurtlar Vadisi.jpg',
      [
        "kurtlarvadisi",
        "kurtlarvadısi",
        "kurtlarvadısı",
      ],
    ),
    Assignment(
      1,
      'La Casa De Papel',
      'Assets/Images/Series/La Casa De Papel.jpg',
      [
        "lacasadepapel",
      ],
    ),
    Assignment(
      1,
      'Lost',
      'Assets/Images/Series/Lost.jpg',
      [
        "lost",
      ],
    ),
    Assignment(
      1,
      'Lucifer',
      'Assets/Images/Series/Lucifer.jpg',
      [
        "lucifer",
        "lucıfer",
      ],
    ),
    Assignment(
      1,
      'Mr. Bean',
      'Assets/Images/Series/Mr. Bean.jpg',
      [
        "mr.bean",
        "mrbean",
        "misterbean",
        "mısterbean",
      ],
    ),
    Assignment(
      1,
      'Mr. Robot',
      'Assets/Images/Series/Mr. Robot.jpg',
      [
        "mr.robot",
        "mrrobot",
        "mister.robot",
        "mıster.robot",
      ],
    ),
    Assignment(
      1,
      'Narcos',
      'Assets/Images/Series/Narcos.jpg',
      [
        "narcos",
      ],
    ),
    Assignment(
      1,
      'Orange Is the New Black',
      'Assets/Images/Series/Orange Is the New Black.jpg',
      [
        "orangeisthenewblack",
        "orangeısthenewblack",
        "orangeisnewblack",
        "orangeısnewblack",
      ],
    ),
    Assignment(
      1,
      'Peaky Blinders',
      'Assets/Images/Series/Peaky Blinders.jpg',
      [
        "peakyblinders",
        "peakyblınders",
      ],
    ),
    Assignment(
      1,
      'Person of Interest',
      'Assets/Images/Series/Person of Interest.jpg',
      [
        "personofınterest",
        "personofinterest",
      ],
    ),
    Assignment(
      1,
      'Planet Earth',
      'Assets/Images/Series/Planet Earth.jpg',
      [
        "planetearth",
      ],
    ),
    Assignment(
      1,
      'Prison Break',
      'Assets/Images/Series/Prison Break.jpg',
      [
        "prisonbreak",
        "prısonbreak",
      ],
    ),
    Assignment(
      1,
      'Rick and Morty',
      'Assets/Images/Series/Rick and Morty.jpg',
      [
        "rickandmorty",
        "rıckandmorty",
        "rickmorty",
        "rıckmorty",
      ],
    ),
    Assignment(
      1,
      'Sense 8',
      'Assets/Images/Series/Sense 8.jpg',
      [
        "sense8",
        "senseeight",
        "senseeıght",
      ],
    ),
    Assignment(
      1,
      'Shameless',
      'Assets/Images/Series/Shameless.jpg',
      [
        "shameless",
      ],
    ),
    Assignment(
      1,
      'Sherlock',
      'Assets/Images/Series/Sherlock.jpg',
      [
        "sherlockholmes",
        "sherlock",
      ],
    ),
    Assignment(
      1,
      'Silicon Walley',
      'Assets/Images/Series/Silicon Walley.jpg',
      [
        "siliconwalley",
        "silıconwalley",
        "sılıconwalley",
      ],
    ),
    Assignment(
      1,
      'Simpsons',
      'Assets/Images/Series/Simpsons.jpg',
      [
        "simpsons",
        "sımpsons",
      ],
    ),
    Assignment(
      1,
      'Sleepy Hollow',
      'Assets/Images/Series/Sleepy Hollow.jpg',
      [
        "sleepyhollow",
      ],
    ),
    Assignment(
      1,
      'South Park',
      'Assets/Images/Series/South Park.jpg',
      [
        "southpark",
      ],
    ),
    Assignment(
      1,
      'Spartacus',
      'Assets/Images/Series/Spartacus.jpg',
      [
        "spartacus",
      ],
    ),
    Assignment(
      1,
      'Stranger Things',
      'Assets/Images/Series/Stranger Things.jpg',
      [
        "strangerthings",
        "strangerthıngs",
      ],
    ),
    Assignment(
      1,
      'Suits',
      'Assets/Images/Series/Suits.jpg',
      [
        "suits",
        "suıts",
      ],
    ),
    Assignment(
      1,
      'Supernatural',
      'Assets/Images/Series/Supernatural.jpg',
      [
        "supernatural",
      ],
    ),
    Assignment(
      1,
      'Suskunlar',
      'Assets/Images/Series/Suskunlar.jpg',
      [
        "suskunlar",
      ],
    ),
    Assignment(
      1,
      'Şahsiyet',
      'Assets/Images/Series/Şahsiyet.jpg',
      [
        "şahsiyet",
        "sahsiyet",
        "sahsıyet",
      ],
    ),
    Assignment(
      1,
      'The 100',
      'Assets/Images/Series/The 100.jpg',
      [
        "the100",
        "theonehundred",
        "onehundred",
        "100",
      ],
    ),
    Assignment(
      1,
      'The Big Bang Theory',
      'Assets/Images/Series/The Big Bang Theory.jpg',
      [
        "thebigbangtheory",
        "thebıgbangtheory"
            "bigbangtheory",
        "bıgbangtheory",
      ],
    ),
    Assignment(
      1,
      'The Boys',
      'Assets/Images/Series/The Boys.jpg',
      [
        "theboys",
        "boys",
      ],
    ),
    Assignment(
      1,
      'The Mentalist',
      'Assets/Images/Series/The Mentalist.jpg',
      [
        "thementalist",
        "thementalıst",
        "mentalist",
        "mentalıst",
      ],
    ),
    Assignment(
      1,
      'The Office',
      'Assets/Images/Series/The Office.jpg',
      [
        "theoffice",
        "theoffıce",
        "office",
        "offıce",
      ],
    ),
    Assignment(
      1,
      'The Originals',
      'Assets/Images/Series/The Originals.jpg',
      [
        "theoriginals",
        "theorıginals",
        "theorıgınals",
        "originals",
        "orıginals",
        "orıgınals",
      ],
    ),
    Assignment(
      1,
      'The Umbrella Academy',
      'Assets/Images/Series/The Umbrella Academy.jpg',
      [
        "theumbrellaacademy",
        "umbrellaacademy",
      ],
    ),
    Assignment(
      1,
      'The Walking Dead',
      'Assets/Images/Series/The Walking Dead.jpg',
      [
        "thewalkingdead",
        "thewalkıngdead",
        "walkingdead",
        "walkıngdead",
      ],
    ),
    Assignment(
      1,
      'The Wire',
      'Assets/Images/Series/The Wire.jpg',
      [
        "thewire",
        "thewıre",
        "wire",
        "wıre",
      ],
    ),
    Assignment(
      1,
      'The Witcher',
      'Assets/Images/Series/The Witcher.jpg',
      [
        "thewitcher",
        "thewıtcher",
        "witcher",
        "wıtcher",
      ],
    ),
    Assignment(
      1,
      'True Detective',
      'Assets/Images/Series/True Detective.jpg',
      [
        "truedetective",
        "truedetectıve",
      ],
    ),
    Assignment(
      1,
      'Vampir Günlükleri',
      'Assets/Images/Series/Vampir Günlükleri.jpg',
      [
        "thevampirediaries",
        "thevampırediaries",
        "thevampıredıaries",
        "thevampıredıarıes",
        "vampirediaries",
        "vampırediaries",
        "vampıredıaries",
        "vampıredıarıes",
        "vampirgünlükleri",
        "vampırgünlükleri",
        "vampırgunlükleri",
        "vampırgunlukleri",
        "vampırgunluklerı",
      ],
    ),
    Assignment(
      1,
      'Vikings',
      'Assets/Images/Series/Vikings.jpg',
      [
        "vikings",
        "vıkings",
        "vıkıngs",
      ],
    ),
    Assignment(
      1,
      'West World',
      'Assets/Images/Series/West World.jpg',
      [
        "westworld",
      ],
    ),
    Assignment(
      1,
      'Yabancı ',
      'Assets/Images/Series/Yabancı.jpg',
      [
        "theoutsider",
        "theoutsıder"
            "outsider",
        "outsıder",
        "yabanci",
        "yabancı",
      ],
    ),
  ],
  [
    ////video oyunları

    //Assignment(2, name, imagePath, keyWords)
    Assignment(
      2,
      "Red Dead Redemption",
      "Assets/Images/Games/red dead redemption.jpg",
      [
        "reddeadredemption",
        "reddeadredemptıon",
        "reddeadredemption2",
        "reddeadredemptıon2",
      ],
    ),
    Assignment(
      2,
      "Witcher",
      "Assets/Images/Games/witcher.jpg",
      [
        "witcher",
        "wıtcher",
        "cadıavcısı",
        "cadiavcısı",
        "cadiavcisı",
        "cadiavcisi",
      ],
    ),
    Assignment(
      2,
      "The God Of War",
      "Assets/Images/Games/god of war.jpg",
      [
        "godofwar",
        "godwar",
      ],
    ),
    Assignment(
      2,
      "The Legends of Zelda",
      "Assets/Images/Games/zelda.jpg",
      ["thelegendsofzelda", "zelda", "thelegendsofzelda"],
    ),
    Assignment(
      2,
      "Battlefield",
      "Assets/Images/Games/battlefield.jpg",
      [
        "battlefield",
        "battlefıeld",
        "bf",
      ],
    ),
    Assignment(
      2,
      "Sea Of Thieves",
      "Assets/Images/Games/sea of thieves.jpg",
      [
        "seaofthieves",
        "seaofthıeves",
        "seathieves",
        "seathıeves",
      ],
    ),
    Assignment(
      2,
      "Farming Simulator",
      "Assets/Images/Games/farming simulator.jpg",
      [
        "farmingsimulator",
        "farmıngsimulator",
        "farmıngsımulator",
        "farmingsimülatör",
        "farmıngsimülatör",
        "farmıngsımülatör",
        "farmıngsımulatör",
        "farmıngsımulator",
        "farmingsimilatör",
        "farmıngsimilatör",
        "farmıngsımilatör",
        "farmıngsımılatör",
        "farmıngsımılator",
      ],
    ),
    Assignment(
      2,
      "Euro Truck Simulator",
      "Assets/Images/Games/euro truck simulator.jpg",
      [
        "eurotrucksimulator",
        "eurotrucksımulator",
        "eurotrucksimülatör",
        "eurotrucksımülatör",
        "eurotrucksımulatör",
        "eurotrucksımulator",
        "eurotruck"
            "ets"
      ],
    ),
    Assignment(
      2,
      "Mortal Kombat",
      "Assets/Images/Games/mortal kombat.jpg",
      [
        "mortalkombat",
        "mortalcombat",
      ],
    ),
    Assignment(
      2,
      "Serious Sam",
      "Assets/Images/Games/serious sam.jpg",
      [
        "serioussam",
        "serıoussam",
        "seriossam",
        "serıossam",
      ],
    ),
    Assignment(
      2,
      "Mafia",
      "Assets/Images/Games/mafia.jpg",
      [
        "mafia",
        "mafıa",
        "mafya",
      ],
    ),
    Assignment(
      2,
      "Rocket League",
      "Assets/Images/Games/rocket league.jpg",
      [
        "rocketleague",
        "rocketlig",
        "rocketlıg",
      ],
    ),
    Assignment(
      2,
      "The Sims",
      "Assets/Images/Games/the sims.jpg",
      [
        "thesims",
        "thesıms",
        "sims",
        "sıms",
      ],
    ),
    Assignment(
      2,
      "Pac Man",
      "Assets/Images/Games/pac-man.jpg",
      [
        "pacman",
      ],
    ),
    Assignment(
      2,
      "Civilization",
      "Assets/Images/Games/civilization.jpg",
      [
        "civilization",
        "cıvilization",
        "cıvılization",
        "cıvılızation",
        "cıvılızatıon",
        "civizilation",
        "cıvizilation",
        "cıvızilation",
        "cıvızılation",
        "cıvızılatıon",
      ],
    ),
    Assignment(
      2,
      "Mount And Blade",
      "Assets/Images/Games/mount and blade.jpg",
      [
        "mountandblade",
        "warband",
        "bannerlord",
      ],
    ),
    Assignment(
      2,
      "Playerunknown's Battlegrounds",
      "Assets/Images/Games/pubg.jpg",
      [
        "pubg",
        "playerunknownsbattlegrounds",
      ],
    ),
    Assignment(
      2,
      "Need For Speed",
      "Assets/Images/Games/need for speed.jpg",
      [
        "needforspeed",
        "mostwanted",
        "underground",
      ],
    ),
    Assignment(
      2,
      "Among Us",
      "Assets/Images/Games/among us.jpg",
      [
        "amongus",
      ],
    ),
    Assignment(
      2,
      "Rainbow Six",
      "Assets/Images/Games/rainbow six.jpg",
      [
        "rainbowsix",
        "raınbowsix",
        "rainbowsıx",
        "raınbowsıx",
        "tomclancy",
      ],
    ),
    Assignment(
      2,
      "NBA 2K",
      "Assets/Images/Games/nba.jpg",
      [
        "nba",
        "nba2k",
      ],
    ),
    Assignment(
      2,
      "Pro Evulation Soccer",
      "Assets/Images/Games/pes.jpg",
      [
        "pes",
        "proevulationsoccer",
        "proevulatıonsoccer",
      ],
    ),
    Assignment(
      2,
      "Fifa",
      "Assets/Images/Games/fifa.jpg",
      [
        "fifa",
        "fıfa",
        "fifa20",
        "fıfa20",
      ],
    ),
    Assignment(
      2,
      "Football Manager",
      "Assets/Images/Games/football manager.jpg",
      [
        "footballmanager",
        "futbolmenajer",
      ],
    ),
    Assignment(
      2,
      "Minecraft",
      "Assets/Images/Games/minecraft.jpg",
      [
        "minecraft",
        "mınecraft",
      ],
    ),
    Assignment(
      2,
      "League of Legends",
      "Assets/Images/Games/league of legends.jpg",
      [
        "leagueoflegends",
        "lol",
      ],
    ),
    Assignment(
      2,
      "Counter Strike",
      "Assets/Images/Games/counter strike.jpg",
      [
        "counterstrike",
        "counterstrıke",
        "csgo",
        "cs",
      ],
    ),
    Assignment(
      2,
      "Pay Day",
      "Assets/Images/Games/pay day.jpg",
      [
        "payday",
        "payday2",
      ],
    ),
    Assignment(
      2,
      "Borderlands",
      "Assets/Images/Games/borderlands.jpg",
      [
        "borderlands",
        "borderlands2",
      ],
    ),
    Assignment(
      2,
      "Injustice",
      "Assets/Images/Games/injustice.jpg",
      [
        "injustice",
        "ınjustice",
        "ınjustıce",
      ],
    ),
    Assignment(
      2,
      "Doom",
      "Assets/Images/Games/doom.jpg",
      [
        "doom",
      ],
    ),
    Assignment(
      2,
      "Age of Empires",
      "Assets/Images/Games/age of empires.jpg",
      ["aoe", "ageofempires", "ageofempıres", "ageof"],
    ),
    Assignment(
      2,
      "Hitman",
      "Assets/Images/Games/hitman.jpg",
      [
        "hitman",
        "hıtman",
      ],
    ),
    Assignment(
      2,
      "Rachet n Clank",
      "Assets/Images/Games/rachet n clank.jpg",
      [
        "rachetandclank",
        "rachetnclank",
      ],
    ),
    Assignment(
      2,
      "Halo",
      "Assets/Images/Games/halo.jpg",
      [
        "halo",
      ],
    ),
    Assignment(
      2,
      "Tomb Raider",
      "Assets/Images/Games/tomb raider.jpg",
      [
        "tombraider",
        "tombraıder",
      ],
    ),
    Assignment(
      2,
      "Street Fighter",
      "Assets/Images/Games/streetfighter.jpg",
      [
        "streetfighter",
        "streetfıghter",
        "streetfigter",
        "streetfıgter",
      ],
    ),
    Assignment(
      2,
      "Forza",
      "Assets/Images/Games/forza.jpg",
      [
        "forzahorizon",
        "forzahorızon",
        "forza",
      ],
    ),
    Assignment(
      2,
      "Pokemon",
      "Assets/Images/Games/pokemon.jpg",
      [
        "pokeman",
        "pokemon",
      ],
    ),
    Assignment(
      2,
      "Thief",
      "Assets/Images/Games/thief.jpg",
      [
        "thief",
        "thıef",
      ],
    ),
    Assignment(
      2,
      "Warcraft",
      "Assets/Images/Games/warcraft.jpg",
      [
        "warcraft",
        "thewarcraft",
      ],
    ),
    Assignment(
      2,
      "Far Cry",
      "Assets/Images/Games/farcry.jpg",
      [
        "farcry",
        "farcry3",
      ],
    ),
    Assignment(
      2,
      "Life is Strange",
      "Assets/Images/Games/life is strange.jpg",
      [
        "lifeisstrange",
        "lıfeisstrange",
        "lıfeısstrange",
        "lifestrange",
        "lıfestrange",
      ],
    ),
    Assignment(
      2,
      "Death Stranding",
      "Assets/Images/Games/death stranding.jpg",
      [
        "deathstranding",
        "deathstrandıng",
        "deathstanding",
        "deathstandıng",
      ],
    ),
    Assignment(
      2,
      "Diablo",
      "Assets/Images/Games/diablo.jpg",
      [
        "diablo",
        "dıablo",
        "şeytan",
        "seytan",
      ],
    ),
    Assignment(
      2,
      "Starcraft",
      "Assets/Images/Games/starcraft.jpg",
      [
        "starcraft",
      ],
    ),
    Assignment(
      2,
      "Championship Manager",
      "Assets/Images/Games/championship manager.jpg",
      [
        "cm",
        "championshipmanager",
        "champıonshipmanager",
        "champıonshıpmanager",
      ],
    ),
    Assignment(
      2,
      "Call of Duty",
      "Assets/Images/Games/call of duty.jpg",
      ["callofduty", "cod", "calofduty"],
    ),
    Assignment(
      2,
      "Assasian's Creed",
      "Assets/Images/Games/assasins creed.jpg",
      [
        "assasianscreed",
        "assasıanscreed",
        "assasian'screed",
        "assasıan'screed",
        "ac",
      ],
    ),
    Assignment(
      2,
      "Dark Souls",
      "Assets/Images/Games/dark souls.jpg",
      [
        "darksouls",
        "darksoul",
        "souls",
      ],
    ),
    Assignment(
      2,
      "Ori",
      "Assets/Images/Games/ori.jpg",
      [
        "ori",
        "orı",
      ],
    ),
    Assignment(
      2,
      "Fallout",
      "Assets/Images/Games/fallout.jpg",
      [
        "fallout",
        "falout",
        "fallout4",
      ],
    ),
    Assignment(
      2,
      "Super Mario",
      "Assets/Images/Games/super mario.jpg",
      [
        "supermario",
        "supermarıo",
        "mario",
        "marıo",
        "mariocard",
        "marıocard",
      ],
    ),
    Assignment(
      2,
      "Max Payne",
      "Assets/Images/Games/max payne.jpg",
      [
        "maxpayne",
        "maxpayne2",
      ],
    ),
    Assignment(
      2,
      "Kingdom Hearts",
      "Assets/Images/Games/kingdom hearts.jpg",
      [
        "kingdomhearts",
        "kıngdomhearts",
        "kingdomofhearts",
        "kıngdomofhearts",
      ],
    ),
    Assignment(
      2,
      "Resident Evil",
      "Assets/Images/Games/resident evil.jpg",
      [
        "residentevil",
        "resıdentevil",
        "resıdentevıl",
        "resıdentevil",
      ],
    ),
    Assignment(
      2,
      "BioShock",
      "Assets/Images/Games/bioshock.jpg",
      [
        "bioshock",
        "bıoshock",
      ],
    ),
    Assignment(
      2,
      "The Walking Dead",
      "Assets/Images/Games/the walking dead.jpg",
      [
        "walkingdead",
        "walkıngdead",
        "thewalkingdead",
        "thewalkıngdead",
        "thewalkingded",
        "thewalkıngded",
      ],
    ),
    Assignment(
      2,
      "Spiderman",
      "Assets/Images/Games/spiderman.jpg",
      [
        "spiderman",
        "spıderman",
      ],
    ),
    Assignment(
      2,
      "Ghost of Tushima",
      "Assets/Images/Games/ghost of tushima.jpg",
      [
        "ghostoftushima",
        "ghostoftushıma",
        "ghostofthushima",
        "ghostofthushıma",
      ],
    ),
    Assignment(
      2,
      "Silent Hill",
      "Assets/Images/Games/silent hill.jpg",
      [
        "silenthill",
        "sılenthill",
        "sılenthıll",
        "silent",
        "sılent",
      ],
    ),
    Assignment(
      2,
      "Batman",
      "Assets/Images/Games/batman.jpg",
      [
        "batmanarkhamcity",
        "batmanarkhamcıty",
        "batman",
        "batmanarkamcity",
        "batmanarkamcıty",
      ],
    ),
    Assignment(
      2,
      "Portal",
      "Assets/Images/Games/portal.jpg",
      [
        "portal",
        "portal2",
      ],
    ),
    Assignment(
      2,
      "Elder Scrolls",
      "Assets/Images/Games/elder scrolls-skyrim.jpg",
      ["skyrim", "skyrım", "oblivion", "oblıvion", "oblıvıon", "elderscrolls"],
    ),
    Assignment(
      2,
      "Bloodborne",
      "Assets/Images/Games/bloodborne.jpg",
      [
        "bloodborne",
        "bloodburn",
      ],
    ),
    Assignment(
      2,
      "Final Fantasy",
      "Assets/Images/Games/final fantasy.jpg",
      [
        "finalfantasy",
        "fınalfantasy",
      ],
    ),
    Assignment(
      2,
      "Star Wars",
      "Assets/Images/Games/starwars.jpg",
      [
        "starwars",
        "starwar",
      ],
    ),
    Assignment(
      2,
      "Mass Effect",
      "Assets/Images/Games/mass effect.jpg",
      [
        "masseffect",
        "massofeffect",
      ],
    ),
    Assignment(
      2,
      "Grand Theft Auto",
      "Assets/Images/Games/gta.jpg",
      [
        "gta",
        "grandtheftauto",
        "grendtheftauto",
      ],
    ),
    Assignment(
      2,
      "Uncharted",
      "Assets/Images/Games/uncharted.jpg",
      [
        "uncharted",
        "uncharted4",
      ],
    ),
    Assignment(
      2,
      "Metal Gear Solid",
      "Assets/Images/Games/metal gear solid.jpg",
      [
        "metalgear",
        "metalgearsolid",
        "metalgearsolıd",
      ],
    ),
    Assignment(
      2,
      "The Last Of Us",
      "Assets/Images/Games/the last of us.jpg",
      [
        "thelastofus",
        "lastofus",
      ],
    ),
  ],
  [
    //kitap

    //Assignment(3, name, imagePath, keyWords)
    Assignment(
      3,
      '1984',
      'Assets/Images/Books/1984.jpg',
      [
        "1984",
        "onenineeightfour",
        "onenıneeightfour",
        "onenıneeıghtfour",
        "birdokuzsekizdört",
        "bırdokuzsekizdört",
        "bırdokuzsekızdört",
        "bırdokuzsekızdort",
        "bindokuzyüzseksendört",
        "bındokuzyüzseksendört",
        "bındokuzyuzseksendört",
        "bındokuzyuzseksendort",
        "onethousandninehundredeightyfour",
        "onethousandnınehundredeightyfour",
        "onethousandnınehundredeıghtyfour",
      ],
    ),
    Assignment(
      3,
      'Ağladığında',
      'Assets/Images/Books/Ağladığında.jpg',
      [
        "ağladığında",
        "agladığında",
        "agladıgında",
        "agladiginda",
      ],
    ),
    Assignment(
      3,
      'Amok Koşucusu',
      'Assets/Images/Books/Amok Koşucusu.jpg',
      [
        "amokkoşucusu",
        "amokkosucusu",
      ],
    ),
    Assignment(
      3,
      "Ay'a Yolculuk ",
      'Assets/Images/Books/Aya Yolculuk.jpg',
      [
        "ayayolculuk",
        "ay'ayolculuk",
      ],
    ),
    Assignment(
      3,
      'Bilinmeyen Bir Kadının Mektubu',
      'Assets/Images/Books/Bilinmeyen Bir Kadının Mektubu.jpg',
      [
        "bilinmeyenbirkadınınmektubu",
        "bılinmeyenbirkadınınmektubu",
        "bılınmeyenbirkadınınmektubu",
        "bılınmeyenbırkadinınmektubu",
        "bılınmeyenbırkadininmektubu",
        "bılınmeyenbırkadınınmektubu",
        "birkadınınmektubu",
        "birkadininmektubu",
        "bırkadınınmektubu",
      ],
    ),
    Assignment(
      3,
      'Bir Çift Ayakkabı',
      'Assets/Images/Books/Bir Çift Ayakkabı.jpg',
      [
        "birçiftayakkabı",
        "birciftayakkabı",
        "bircıftayakkabı",
        "bircıftayakkabı",
        "bircıftayakkabi",
        "bırcıftayakkabı",
      ],
    ),
    Assignment(
      3,
      'Çalıkuşu',
      'Assets/Images/Books/Çalıkuşu.jpg',
      [
        "çalıkuşu",
        "calıkuşu",
        "calikuşu",
        "calikusu",
        "calıkusu",
      ],
    ),
    Assignment(
      3,
      'Çavdar Tarlasında Çocuklar',
      'Assets/Images/Books/Çavdar Tarlasında Çocuklar.jpg',
      [
        "çavdartarlasındaçocuklar",
        "cavdartarlasındaçocuklar",
        "cavdartarlasindaçocuklar",
        "cavdartarlasindacocuklar",
      ],
    ),
    Assignment(
      3,
      'Kozmos',
      'Assets/Images/Books/Kozmos.jpg',
      [
        "kozmos",
        "cosmos",
      ],
    ),
    Assignment(
      3,
      'Kör Baykuş',
      'Assets/Images/Books/Kör Baykuş.jpg',
      [
        "körbaykuş",
        "korbaykuş",
        "korbaykus",
      ],
    ),
    Assignment(
      3,
      'Moby Dıck',
      'Assets/Images/Books/Moby Dıck.jpg',
      [
        "mobydıck",
        "mobydick",
      ],
    ),
    Assignment(
      3,
      'Dijital Kale',
      'Assets/Images/Books/Dijital Kale.jpg',
      [
        "dijitalkale",
        "dıjitalkale",
        "dıjıtalkale",
      ],
    ),
    Assignment(
      3,
      'Silahlara Veda',
      'Assets/Images/Books/Silahlara Veda.jpg',
      [
        "silahlaraveda",
        "sılahlaraveda",
      ],
    ),
    Assignment(
      3,
      'Dava',
      'Assets/Images/Books/Dava.jpg',
      [
        "dava",
      ],
    ),
    Assignment(
      3,
      'Deniz Feneri',
      'Assets/Images/Books/Deniz Feneri.jpg',
      [
        "denizfeneri",
        "denızfeneri",
        "denızfenerı",
      ],
    ),
    Assignment(
      3,
      'Diriliş ',
      'Assets/Images/Books/Diriliş.jpg',
      [
        "diriliş",
        "dirilis",
        "dırılıs",
      ],
    ),
    Assignment(
      3,
      'Beyaz Diş',
      'Assets/Images/Books/Beyaz Diş.jpg',
      [
        "beyazdiş",
        "beyazdış",
        "beyazdis",
        "beyazdıs",
      ],
    ),
    Assignment(
      3,
      'Fransız Teğmenin Kadını',
      'Assets/Images/Books/Fransız Teğmenin Kadını.jpg',
      [
        "fransızteğmeninkadını",
        "fransizteğmeninkadını",
        "fransiztegmeninkadını",
        "fransiztegmenınkadını",
        "fransiztegmenınkadinı",
        "fransiztegmenınkadini",
        "fransıztegmenınkadını",
      ],
    ),
    Assignment(
      3,
      'Don Kişot',
      'Assets/Images/Books/Don Kişot.jpg',
      [
        "donkişot",
        "donkışot",
        "donkisot",
        "donkısot",
      ],
    ),
    Assignment(
      3,
      'Da Vıncı Şifresi',
      'Assets/Images/Books/Da Vıncı Şifresi.jpg',
      [
        "davıncışifresi",
        "davincışifresi",
        "davincişifresi",
        "davincisifresi",
        "davincisıfresi",
        "davincisıfresı",
        "davıncisıfresı",
        "davıncısıfresı",
      ],
    ),
    Assignment(
      3,
      'Dönüşüm',
      'Assets/Images/Books/Dönüşüm.jpg',
      [
        "dönüşüm",
        "donüşüm",
        "donuşüm",
        "donusüm",
        "donusum",
        "dönusum",
      ],
    ),
    Assignment(
      3,
      'Harry Potter ve Ateş Kadehi',
      'Assets/Images/Books/Harry Potter ve Ateş Kadehi.jpg',
      [
        "harrypotterveateşkadehi",
        "harrypotterveateskadehi",
        "harrypotterveateskadehı",
        "harrypotterateşkadehi",
        "harrypotterateskadehi",
        "harrypotterateskadehı",
        "harrypotter",
      ],
    ),
    Assignment(
      3,
      'Fahrenheit 451',
      'Assets/Images/Books/Fahrenheit 451.jpg',
      [
        "fahrenheit451",
        "fahrenheıt451",
        "fahrenheit",
        "fahrenheıt",
      ],
    ),
    Assignment(
      3,
      'Fareler ve İnsanlar',
      'Assets/Images/Books/Fareler ve İnsanlar.jpg',
      [
        "farelerveinsanlar",
        "farelerveınsanlar",
      ],
    ),
    Assignment(
      3,
      'Gazap Üzümleri',
      'Assets/Images/Books/Gazap Üzümleri.jpg',
      [
        "gazapüzümleri",
        "gazapuzümleri",
        "gazapuzumleri",
        "gazapuzumlerı",
      ],
    ),
    Assignment(
      3,
      "Palto",
      'Assets/Images/Books/Gogolun Paltosu.jpg',
      [
        "palto",
        "gogol'unpaltosu",
        "gogolunpaltosu",
      ],
    ),
    Assignment(
      3,
      'Guguk Kuşu',
      'Assets/Images/Books/Guguk Kuşu.jpg',
      [
        "gugukkuşu",
        "gugukkusu",
      ],
    ),
    Assignment(
      3,
      'İnce Memed',
      'Assets/Images/Books/İnce Memed.jpg',
      [
        "incememed",
        "ıncememed",
      ],
    ),
    Assignment(
      3,
      'Kar',
      'Assets/Images/Books/Kar.jpg',
      [
        "kar",
      ],
    ),
    Assignment(
      3,
      'Kara Kitap',
      'Assets/Images/Books/Kara Kitap.jpg',
      [
        "karakitap",
        "karakıtap",
      ],
    ),
    Assignment(
      3,
      'Karanlığın Yüreği',
      'Assets/Images/Books/Karanlığın Yüreği.jpg',
      [
        "karanlığınyüreği",
        "karanlıgınyüreği",
        "karanlıgınyüregi",
        "karanlıgınyuregi",
      ],
    ),
    Assignment(
      3,
      'Kiralık Konak',
      'Assets/Images/Books/Kiralık Konak.jpg',
      [
        "kiralıkkonak",
        "kıralikkonak",
        "kıralıkkonak",
      ],
    ),
    Assignment(
      3,
      'Kırmızı Saçlı Kadın',
      'Assets/Images/Books/Kırmızı Saçlı Kadın.jpg',
      [
        "kırmızısaçlıkadın",
        "kirmızısaçlıkadın",
        "kirmizısaçlıkadın",
        "kirmizisaçlıkadın",
        "kirmizisaclıkadın",
        "kirmizisaclikadın",
        "kirmizisaclikadin",
        "kırmızısaclıkadın",
      ],
    ),
    Assignment(
      3,
      'Kırmızı ve Siyah',
      'Assets/Images/Books/Kırmızı ve Siyah.jpg',
      [
        "kırmızıvesiyah",
        "kirmızıvesiyah",
        "kirmizıvesiyah",
        "kirmizivesiyah",
        "kirmizivesıyah",
        "kırmızıvesıyah",
      ],
    ),
    Assignment(
      3,
      'Kumarbaz',
      'Assets/Images/Books/Kumarbaz.jpg',
      [
        "kumarbaz",
      ],
    ),
    Assignment(
      3,
      'Kurtlarla Koşan Kadınlar',
      'Assets/Images/Books/Kurtlarla Koşan Kadınlar.jpg',
      [
        "kurtlarlakoşankadınlar",
        "kurtlarlakosankadınlar",
        "kurtlarlakosankadinlar",
        "kurtlarlakosankadınlar",
      ],
    ),
    Assignment(
      3,
      'Küçük Prens',
      'Assets/Images/Books/Küçük Prens.jpg',
      [
        "küçükprens",
        "kuçükprens",
        "kucükprens",
        "kucukprens",
      ],
    ),
    Assignment(
      3,
      'Kürk Mantolu Madonna',
      'Assets/Images/Books/Kürk Mantolu Madonna.jpg',
      [
        "kürkmantolumadonna",
        "kurkmantolumadonna",
      ],
    ),
    Assignment(
      3,
      'Martı',
      'Assets/Images/Books/Martı.jpg',
      [
        "martı",
        "marti",
      ],
    ),
    Assignment(
      3,
      'Melekler ve Şeytanlar',
      'Assets/Images/Books/Melekler ve Şeytanlar.jpg',
      [
        "meleklerveşeytanlar",
        "meleklerveseytanlar",
        "meleklerşeytanlar",
        "meleklerseytanlar",
      ],
    ),
    Assignment(
      3,
      'Momo',
      'Assets/Images/Books/Momo.jpg',
      [
        "momo",
      ],
    ),
    Assignment(
      3,
      'Origin',
      'Assets/Images/Books/Origin.jpg',
      [
        "origin",
        "orıgin",
        "origın",
        "orıgın",
      ],
    ),
    Assignment(
      3,
      'Otomatik Portakal',
      'Assets/Images/Books/Otomatik Portakal.jpg',
      [
        "otomatikportakal",
        "otomatıkportakal",
      ],
    ),
    Assignment(
      3,
      'Otostopçunun Galaksi Rehberi',
      'Assets/Images/Books/Otostopçunun Galaksi Rehberi.jpg',
      [
        "otostopçunungalaksirehberi",
        "otostopcunungalaksirehberi",
        "otostopcunungalaksırehberi",
        "otostopcunungalaksırehberı",
      ],
    ),
    Assignment(
      3,
      'Outliers',
      'Assets/Images/Books/Outliers.jpg',
      [
        "outliers",
        "outlıers",
      ],
    ),
    Assignment(
      3,
      'Saatleri Ayarlama Enstitüsü',
      'Assets/Images/Books/Saatleri Ayarlama Enstitüsü.jpg',
      [
        "saatleriayarlamaenstitüsü",
        "saatlerıayarlamaenstitüsü",
        "saatlerıayarlamaenstıtüsü",
        "saatlerıayarlamaenstıtusü",
        "saatlerıayarlamaenstıtusu",
      ],
    ),
    Assignment(
      3,
      'Satranç',
      'Assets/Images/Books/Satranç.jpg',
      [
        "satranç",
        "satranc",
      ],
    ),
    Assignment(
      3,
      'Savaş ve Barış',
      'Assets/Images/Books/Savaş ve Barış.jpg',
      [
        "savaşvebarış",
        "savasvebarış",
        "savasvebariş",
        "savasvebaris",
        "savasvebarıs",
      ],
    ),
    Assignment(
      3,
      'Sefiller',
      'Assets/Images/Books/Sefiller.jpg',
      [
        "sefiller",
        "sefıller",
      ],
    ),
    Assignment(
      3,
      'Simyacı',
      'Assets/Images/Books/Simyacı.jpg',
      [
        "simyacı",
        "sımyacı",
        "sımyaci",
        "sımyacı",
      ],
    ),
    Assignment(
      3,
      'Sineklerin Tanrısı',
      'Assets/Images/Books/Sineklerin Tanrısı.jpg',
      [
        "sineklerintanrısı",
        "sıneklerintanrısı",
        "sıneklerıntanrısı",
        "sıneklerıntanrisı",
        "sıneklerıntanrisi",
        "sineklerintanrisi",
      ],
    ),
    Assignment(
      3,
      'Sırça Köşk',
      'Assets/Images/Books/Sırça Köşk.jpg',
      [
        "sırçaköşk",
        "sırcaköşk",
        "sırcakoşk",
        "sırcakosk",
      ],
    ),
    Assignment(
      3,
      'Son Ada',
      'Assets/Images/Books/Son Ada.jpg',
      [
        "sonada",
      ],
    ),
    Assignment(
      3,
      'Son Kuşlar',
      'Assets/Images/Books/Son Kuşlar.jpg',
      [
        "sonkuşlar",
        "sonkuslar",
      ],
    ),
    Assignment(
      3,
      'Suç ve Ceza',
      'Assets/Images/Books/Suç ve Ceza.jpg',
      [
        "suçveceza",
        "sucveceza",
      ],
    ),
    Assignment(
      3,
      'Şeker Portakalı',
      'Assets/Images/Books/Şeker Portakalı.jpg',
      [
        "şekerportakalı",
        "sekerportakalı",
        "sekerportakali",
      ],
    ),
    Assignment(
      3,
      'Tatar Çölü',
      'Assets/Images/Books/Tatar Çölü.jpg',
      [
        "tatarçölü",
        "tatarcölü",
        "tatarcolü",
        "tatarcolu",
      ],
    ),
    Assignment(
      3,
      'Tutunamayanlar',
      'Assets/Images/Books/Tutunamayanlar.jpg',
      [
        "tutunamayanlar",
      ],
    ),
    Assignment(
      3,
      'Tüfek Mikrop ve Çelik',
      'Assets/Images/Books/Tüfek Mikrop ve Çelik.jpg',
      [
        "tüfekmikropveçelik",
        "tufekmikropveçelik",
        "tufekmıkropveçelik",
        "tufekmıkropvecelik",
        "tufekmıkropvecelık",
      ],
    ),
    Assignment(
      3,
      'Türlerin Kökeni',
      'Assets/Images/Books/Türlerin Kökeni.jpg',
      [
        "türlerinkökeni",
        "turlerinkökeni",
        "turlerınkökeni",
        "turlerınkokeni",
        "turlerınkokenı",
      ],
    ),
    Assignment(
      3,
      'Uçurtma Avcısı',
      'Assets/Images/Books/Uçurtma Avcısı.jpg',
      [
        "uçurtmaavcısı",
        "ucurtmaavcısı",
        "ucurtmaavcisı",
        "ucurtmaavcisi",
      ],
    ),
    Assignment(
      3,
      'Üç Silahşör',
      'Assets/Images/Books/Üç Silahşör.jpg',
      [
        "üçsilahşör",
        "ücsilahşör",
        "ücsılahşör",
        "ücsılahsör",
        "ücsılahsor",
        "üçsilahşörler",
        "uçsilahşörler",
        "uçsilahşörler",
        "uçsılahşörler",
        "uçsılahsörler",
        "uçsılahsorler",
      ],
    ),
    Assignment(
      3,
      'Vadideki Zambak',
      'Assets/Images/Books/Vadideki Zambak.jpg',
      [
        "vadidekizambak",
        "vadıdekizambak",
        "vadıdekızambak",
      ],
    ),
    Assignment(
      3,
      'Yaban',
      'Assets/Images/Books/Yaban.jpg',
      [
        "yaban",
      ],
    ),
    Assignment(
      3,
      'Yaşlı Adam ve Deniz',
      'Assets/Images/Books/Yaşlı Adam ve Deniz.jpg',
      [
        "yaşlıadamvedeniz",
        "yaslıadamvedeniz",
        "yasliadamvedeniz",
        "yasliadamvedenız",
      ],
    ),
    Assignment(
      3,
      'Yeraltından Notlar',
      'Assets/Images/Books/Yeraltından Notlar.jpg',
      [
        "yeraltındannotlar",
        "yeraltindannotlar",
      ],
    ),
    Assignment(
      3,
      'Zar Adam',
      'Assets/Images/Books/Zar Adam.jpg',
      [
        "zaradam",
      ],
    ),
  ],
  //[
  //şarkı
  //Assignment(category, name, imagePath, keyWords)
  // ],
];
